In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("dataset.csv",encoding="shift-jis")

In [3]:
df

季節   月    最高    最低  燃焼時間1日  燃焼回数回数  燃焼回数1日
0     2  11  35.5  11.5     0.0     NaN     1.0
1     2  11  35.0  11.5     0.0    15.0    14.0
2     2  11  36.0  11.5     1.0    27.0    12.0
3     2  11  35.5  12.0     0.0    31.0     4.0
4     2  11  37.5  14.5     0.0    31.0     0.0
5     2  11  31.0  16.5     0.0    31.0     0.0
6     2  11   NaN   NaN     0.0    31.0     NaN
7     2  11   NaN   NaN     0.0    31.0     NaN
8     2  11  40.0  12.5     1.0    40.0     9.0
9     2  11  37.0  12.5     0.0    48.0     8.0
10    2  11  36.5  13.0     1.0    61.0    13.0
11    2  11  29.5  16.0     0.0    61.0     0.0
12    2  11  27.5  17.5     0.0    61.0     0.0
13    2  11  35.5  14.5     0.0    61.0     0.0
14    2  11  36.0  16.0     0.0    61.0     0.0
15    2  11  30.0  16.0     0.0    61.0     0.0
16    2  11  29.0  14.0     0.0    61.0     0.0
17    2  11  31.0  16.5     0.0    61.0     0.0
18    2  11  28.5  13.0     1.0    68.0     7.0
19    2  11  35.0  13.0     0.0    69.0     1.0
20    2  11  34.0  14.0     0.0    69.0     0.0
21    2  11  27.5  15.0     0.0    69.0     0.0
22    2  11   NaN   NaN    -4.0    69.0     NaN
23    2  11  35.0  13.0     7.0    80.0    11.0
24    2  11  31.0  13.5     3.0   105.0    25.0
25    2  11  31.0  13.5     1.0   124.0    19.0
26    2  11  25.5  13.5     2.0   145.0    21.0
27    2  11  29.0  14.0     4.0   171.0    26.0
28    2  11  31.0  14.0     2.0   187.0    16.0
29    0  12  30.0  14.0     3.0   213.0    26.0
..   ..  ..   ...   ...     ...     ...     ...
151   1   4  29.0  17.5   472.0  3182.0    16.0
152   1   4  33.5  19.0   473.0  3198.0    16.0
153   1   4  28.0  18.0   476.0  3214.0    16.0
154   1   4  28.0  16.5   478.0  3230.0    16.0
155   1   4  32.5  13.0   480.0  3247.0    17.0
156   1   4  30.5  16.5   482.0  3265.0    18.0
157   1   4  19.5  16.5   484.0  3281.0    16.0
158   1   4  32.5  13.5   486.0  3298.0    17.0
159   1   4   NaN   NaN     NaN  3315.0    17.0
160   1   4  34.0  14.5   489.0  3331.0    16.0
161   1   4  31.0  13.5   491.0  3349.0    18.0
162   1   4  32.5  18.0   493.0  3365.0    16.0
163   1   4  26.0  18.0   495.0  3381.0    16.0
164   1   4  35.5  17.5   497.0  3397.0    16.0
165   1   4  33.0  14.0   498.0  3414.0    17.0
166   1   4  35.0  18.0   500.0  3430.0    16.0
167   1   4  27.0  16.5   502.0  3446.0    16.0
168   1   4  28.5  13.5   504.0  3465.0    19.0
169   1   4  34.5  13.5   506.0  3482.0    17.0
170   1   4  34.5  17.5   507.0  3498.0    16.0
171   1   4  30.5  18.0   509.0  3514.0    16.0
172   1   4  36.0  17.5   511.0  3530.0    16.0
173   1   4  42.0  18.5   512.0  3546.0    16.0
174   1   4  36.5  18.0   514.0  3562.0    16.0
175   1   4  36.0  17.5   516.0  3578.0    16.0
176   1   4  38.0  18.0   517.0  3594.0    16.0
177   1   4  30.5  18.0   519.0  3610.0    16.0
178   1   4  30.5  15.5   520.0  3626.0    16.0
179   1   4  34.5  13.5   522.0  3659.0    33.0
180   1   4  35.0  16.0   524.0  3675.0    16.0

[181 rows x 7 columns]

In [4]:
dfd=df.dropna()

In [5]:
dfd

季節   月    最高    最低  燃焼時間1日  燃焼回数回数  燃焼回数1日
1     2  11  35.0  11.5     0.0    15.0    14.0
2     2  11  36.0  11.5     1.0    27.0    12.0
3     2  11  35.5  12.0     0.0    31.0     4.0
4     2  11  37.5  14.5     0.0    31.0     0.0
5     2  11  31.0  16.5     0.0    31.0     0.0
8     2  11  40.0  12.5     1.0    40.0     9.0
9     2  11  37.0  12.5     0.0    48.0     8.0
10    2  11  36.5  13.0     1.0    61.0    13.0
11    2  11  29.5  16.0     0.0    61.0     0.0
12    2  11  27.5  17.5     0.0    61.0     0.0
13    2  11  35.5  14.5     0.0    61.0     0.0
14    2  11  36.0  16.0     0.0    61.0     0.0
15    2  11  30.0  16.0     0.0    61.0     0.0
16    2  11  29.0  14.0     0.0    61.0     0.0
17    2  11  31.0  16.5     0.0    61.0     0.0
18    2  11  28.5  13.0     1.0    68.0     7.0
19    2  11  35.0  13.0     0.0    69.0     1.0
20    2  11  34.0  14.0     0.0    69.0     0.0
21    2  11  27.5  15.0     0.0    69.0     0.0
23    2  11  35.0  13.0     7.0    80.0    11.0
24    2  11  31.0  13.5     3.0   105.0    25.0
25    2  11  31.0  13.5     1.0   124.0    19.0
26    2  11  25.5  13.5     2.0   145.0    21.0
27    2  11  29.0  14.0     4.0   171.0    26.0
28    2  11  31.0  14.0     2.0   187.0    16.0
29    0  12  30.0  14.0     3.0   213.0    26.0
30    0  12  32.0  15.0     2.0   216.0     3.0
31    0  12  25.5  14.0     3.0   239.0    23.0
32    0  12  21.0  14.0     3.0   268.0    29.0
33    0  12  29.0  13.5     3.0   299.0    31.0
..   ..  ..   ...   ...     ...     ...     ...
150   1   3  33.5  14.5     2.0  3166.0    17.0
151   1   4  29.0  17.5   472.0  3182.0    16.0
152   1   4  33.5  19.0   473.0  3198.0    16.0
153   1   4  28.0  18.0   476.0  3214.0    16.0
154   1   4  28.0  16.5   478.0  3230.0    16.0
155   1   4  32.5  13.0   480.0  3247.0    17.0
156   1   4  30.5  16.5   482.0  3265.0    18.0
157   1   4  19.5  16.5   484.0  3281.0    16.0
158   1   4  32.5  13.5   486.0  3298.0    17.0
160   1   4  34.0  14.5   489.0  3331.0    16.0
161   1   4  31.0  13.5   491.0  3349.0    18.0
162   1   4  32.5  18.0   493.0  3365.0    16.0
163   1   4  26.0  18.0   495.0  3381.0    16.0
164   1   4  35.5  17.5   497.0  3397.0    16.0
165   1   4  33.0  14.0   498.0  3414.0    17.0
166   1   4  35.0  18.0   500.0  3430.0    16.0
167   1   4  27.0  16.5   502.0  3446.0    16.0
168   1   4  28.5  13.5   504.0  3465.0    19.0
169   1   4  34.5  13.5   506.0  3482.0    17.0
170   1   4  34.5  17.5   507.0  3498.0    16.0
171   1   4  30.5  18.0   509.0  3514.0    16.0
172   1   4  36.0  17.5   511.0  3530.0    16.0
173   1   4  42.0  18.5   512.0  3546.0    16.0
174   1   4  36.5  18.0   514.0  3562.0    16.0
175   1   4  36.0  17.5   516.0  3578.0    16.0
176   1   4  38.0  18.0   517.0  3594.0    16.0
177   1   4  30.5  18.0   519.0  3610.0    16.0
178   1   4  30.5  15.5   520.0  3626.0    16.0
179   1   4  34.5  13.5   522.0  3659.0    33.0
180   1   4  35.0  16.0   524.0  3675.0    16.0

[172 rows x 7 columns]

In [8]:
dfd2=dfd.drop("月",axis=1)
dfd2

季節    最高    最低  燃焼時間1日  燃焼回数回数  燃焼回数1日
1     2  35.0  11.5     0.0    15.0    14.0
2     2  36.0  11.5     1.0    27.0    12.0
3     2  35.5  12.0     0.0    31.0     4.0
4     2  37.5  14.5     0.0    31.0     0.0
5     2  31.0  16.5     0.0    31.0     0.0
8     2  40.0  12.5     1.0    40.0     9.0
9     2  37.0  12.5     0.0    48.0     8.0
10    2  36.5  13.0     1.0    61.0    13.0
11    2  29.5  16.0     0.0    61.0     0.0
12    2  27.5  17.5     0.0    61.0     0.0
13    2  35.5  14.5     0.0    61.0     0.0
14    2  36.0  16.0     0.0    61.0     0.0
15    2  30.0  16.0     0.0    61.0     0.0
16    2  29.0  14.0     0.0    61.0     0.0
17    2  31.0  16.5     0.0    61.0     0.0
18    2  28.5  13.0     1.0    68.0     7.0
19    2  35.0  13.0     0.0    69.0     1.0
20    2  34.0  14.0     0.0    69.0     0.0
21    2  27.5  15.0     0.0    69.0     0.0
23    2  35.0  13.0     7.0    80.0    11.0
24    2  31.0  13.5     3.0   105.0    25.0
25    2  31.0  13.5     1.0   124.0    19.0
26    2  25.5  13.5     2.0   145.0    21.0
27    2  29.0  14.0     4.0   171.0    26.0
28    2  31.0  14.0     2.0   187.0    16.0
29    0  30.0  14.0     3.0   213.0    26.0
30    0  32.0  15.0     2.0   216.0     3.0
31    0  25.5  14.0     3.0   239.0    23.0
32    0  21.0  14.0     3.0   268.0    29.0
33    0  29.0  13.5     3.0   299.0    31.0
..   ..   ...   ...     ...     ...     ...
150   1  33.5  14.5     2.0  3166.0    17.0
151   1  29.0  17.5   472.0  3182.0    16.0
152   1  33.5  19.0   473.0  3198.0    16.0
153   1  28.0  18.0   476.0  3214.0    16.0
154   1  28.0  16.5   478.0  3230.0    16.0
155   1  32.5  13.0   480.0  3247.0    17.0
156   1  30.5  16.5   482.0  3265.0    18.0
157   1  19.5  16.5   484.0  3281.0    16.0
158   1  32.5  13.5   486.0  3298.0    17.0
160   1  34.0  14.5   489.0  3331.0    16.0
161   1  31.0  13.5   491.0  3349.0    18.0
162   1  32.5  18.0   493.0  3365.0    16.0
163   1  26.0  18.0   495.0  3381.0    16.0
164   1  35.5  17.5   497.0  3397.0    16.0
165   1  33.0  14.0   498.0  3414.0    17.0
166   1  35.0  18.0   500.0  3430.0    16.0
167   1  27.0  16.5   502.0  3446.0    16.0
168   1  28.5  13.5   504.0  3465.0    19.0
169   1  34.5  13.5   506.0  3482.0    17.0
170   1  34.5  17.5   507.0  3498.0    16.0
171   1  30.5  18.0   509.0  3514.0    16.0
172   1  36.0  17.5   511.0  3530.0    16.0
173   1  42.0  18.5   512.0  3546.0    16.0
174   1  36.5  18.0   514.0  3562.0    16.0
175   1  36.0  17.5   516.0  3578.0    16.0
176   1  38.0  18.0   517.0  3594.0    16.0
177   1  30.5  18.0   519.0  3610.0    16.0
178   1  30.5  15.5   520.0  3626.0    16.0
179   1  34.5  13.5   522.0  3659.0    33.0
180   1  35.0  16.0   524.0  3675.0    16.0

[172 rows x 6 columns]

In [9]:
y=dfd2["季節"].values
x=dfd2.drop("季節",axis=1).values

In [10]:
y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [11]:
x

array([[3.500e+01, 1.150e+01, 0.000e+00, 1.500e+01, 1.400e+01],
       [3.600e+01, 1.150e+01, 1.000e+00, 2.700e+01, 1.200e+01],
       [3.550e+01, 1.200e+01, 0.000e+00, 3.100e+01, 4.000e+00],
       [3.750e+01, 1.450e+01, 0.000e+00, 3.100e+01, 0.000e+00],
       [3.100e+01, 1.650e+01, 0.000e+00, 3.100e+01, 0.000e+00],
       [4.000e+01, 1.250e+01, 1.000e+00, 4.000e+01, 9.000e+00],
       [3.700e+01, 1.250e+01, 0.000e+00, 4.800e+01, 8.000e+00],
       [3.650e+01, 1.300e+01, 1.000e+00, 6.100e+01, 1.300e+01],
       [2.950e+01, 1.600e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [2.750e+01, 1.750e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [3.550e+01, 1.450e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [3.600e+01, 1.600e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [3.000e+01, 1.600e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [2.900e+01, 1.400e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [3.100e+01, 1.650e+01, 0.000e+00, 6.100e+01, 0.000e+00],
       [2.850e+01, 1.300e+01, 1.000e+00,

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [15]:
x2=preprocessing.minmax_scale(x)

In [16]:
x2

array([[0.72      , 0.        , 0.        , 0.        , 0.25454545],
       [0.76      , 0.        , 0.0019084 , 0.00327869, 0.21818182],
       [0.74      , 0.06666667, 0.        , 0.00437158, 0.07272727],
       [0.82      , 0.4       , 0.        , 0.00437158, 0.        ],
       [0.56      , 0.66666667, 0.        , 0.00437158, 0.        ],
       [0.92      , 0.13333333, 0.0019084 , 0.0068306 , 0.16363636],
       [0.8       , 0.13333333, 0.        , 0.00901639, 0.14545455],
       [0.78      , 0.2       , 0.0019084 , 0.01256831, 0.23636364],
       [0.5       , 0.6       , 0.        , 0.01256831, 0.        ],
       [0.42      , 0.8       , 0.        , 0.01256831, 0.        ],
       [0.74      , 0.4       , 0.        , 0.01256831, 0.        ],
       [0.76      , 0.6       , 0.        , 0.01256831, 0.        ],
       [0.52      , 0.6       , 0.        , 0.01256831, 0.        ],
       [0.48      , 0.33333333, 0.        , 0.01256831, 0.        ],
       [0.56      , 0.66666667, 0.

In [17]:
model=RandomForestClassifier(n_estimators=10)

In [18]:
model.fit(x,y)
imp=model.feature_importances_
imp

array([0.08802246, 0.05230702, 0.24436346, 0.43418277, 0.18112429])

In [19]:
name=["最高","最低","燃焼時間1日","燃焼回数回数","燃焼回数1日"]

In [24]:
out=[]
out.append(name)
out.append(imp)
import numpy as np
out=np.array(out).T
impdf=pd.DataFrame(out)
impdf

0                     1
0      最高   0.08802245519963986
1      最低  0.052307015448920954
2  燃焼時間1日    0.2443634614200691
3  燃焼回数回数   0.43418277354662116
4  燃焼回数1日   0.18112429438474892

In [25]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [32]:
model=LDA(n_components=len(x2[0]),store_covariance=True)

In [33]:
model.fit(x2,y)

LinearDiscriminantAnalysis(n_components=5, priors=None, shrinkage=None,
              solver='svd', store_covariance=True, tol=0.0001)

In [42]:
imp2=model.coef_
out2=[]
out2.append(name)
for i in range(len(imp2)):
    out2.append(imp2[i])
out2=np.array(out2).T
dfo=pd.DataFrame(out2)
dfo.columns=["項目","冬係数","春係数","秋係数"]
dfo

項目                  冬係数                  春係数                  秋係数
0      最高  -3.2031263387247875   3.3136483109287322    4.236807656477868
1      最低  -0.5897242103700626   3.1151708163775345   -4.831386502938653
2  燃焼時間1日  -0.8672450750645773   0.6893637064740181   1.6125973707332615
3  燃焼回数回数     -4.2869208759377   16.029092270108936  -20.300774696630807
4  燃焼回数1日   3.5733339585439152  -0.4781515510285952  -11.935876134795807

In [44]:
dfo.to_csv("係数.csv",encoding="shift-jis")
impdf.to_csv("特徴重要度.csv",encoding="shift-jis")

In [45]:
dfd3=dfd2.drop("季節",axis=1)
dfd3

最高    最低  燃焼時間1日  燃焼回数回数  燃焼回数1日
1    35.0  11.5     0.0    15.0    14.0
2    36.0  11.5     1.0    27.0    12.0
3    35.5  12.0     0.0    31.0     4.0
4    37.5  14.5     0.0    31.0     0.0
5    31.0  16.5     0.0    31.0     0.0
8    40.0  12.5     1.0    40.0     9.0
9    37.0  12.5     0.0    48.0     8.0
10   36.5  13.0     1.0    61.0    13.0
11   29.5  16.0     0.0    61.0     0.0
12   27.5  17.5     0.0    61.0     0.0
13   35.5  14.5     0.0    61.0     0.0
14   36.0  16.0     0.0    61.0     0.0
15   30.0  16.0     0.0    61.0     0.0
16   29.0  14.0     0.0    61.0     0.0
17   31.0  16.5     0.0    61.0     0.0
18   28.5  13.0     1.0    68.0     7.0
19   35.0  13.0     0.0    69.0     1.0
20   34.0  14.0     0.0    69.0     0.0
21   27.5  15.0     0.0    69.0     0.0
23   35.0  13.0     7.0    80.0    11.0
24   31.0  13.5     3.0   105.0    25.0
25   31.0  13.5     1.0   124.0    19.0
26   25.5  13.5     2.0   145.0    21.0
27   29.0  14.0     4.0   171.0    26.0
28   31.0  14.0     2.0   187.0    16.0
29   30.0  14.0     3.0   213.0    26.0
30   32.0  15.0     2.0   216.0     3.0
31   25.5  14.0     3.0   239.0    23.0
32   21.0  14.0     3.0   268.0    29.0
33   29.0  13.5     3.0   299.0    31.0
..    ...   ...     ...     ...     ...
150  33.5  14.5     2.0  3166.0    17.0
151  29.0  17.5   472.0  3182.0    16.0
152  33.5  19.0   473.0  3198.0    16.0
153  28.0  18.0   476.0  3214.0    16.0
154  28.0  16.5   478.0  3230.0    16.0
155  32.5  13.0   480.0  3247.0    17.0
156  30.5  16.5   482.0  3265.0    18.0
157  19.5  16.5   484.0  3281.0    16.0
158  32.5  13.5   486.0  3298.0    17.0
160  34.0  14.5   489.0  3331.0    16.0
161  31.0  13.5   491.0  3349.0    18.0
162  32.5  18.0   493.0  3365.0    16.0
163  26.0  18.0   495.0  3381.0    16.0
164  35.5  17.5   497.0  3397.0    16.0
165  33.0  14.0   498.0  3414.0    17.0
166  35.0  18.0   500.0  3430.0    16.0
167  27.0  16.5   502.0  3446.0    16.0
168  28.5  13.5   504.0  3465.0    19.0
169  34.5  13.5   506.0  3482.0    17.0
170  34.5  17.5   507.0  3498.0    16.0
171  30.5  18.0   509.0  3514.0    16.0
172  36.0  17.5   511.0  3530.0    16.0
173  42.0  18.5   512.0  3546.0    16.0
174  36.5  18.0   514.0  3562.0    16.0
175  36.0  17.5   516.0  3578.0    16.0
176  38.0  18.0   517.0  3594.0    16.0
177  30.5  18.0   519.0  3610.0    16.0
178  30.5  15.5   520.0  3626.0    16.0
179  34.5  13.5   522.0  3659.0    33.0
180  35.0  16.0   524.0  3675.0    16.0

[172 rows x 5 columns]

In [47]:
y2=dfd3["燃焼回数回数"].values
dfd3_x=dfd3.drop("燃焼回数回数",axis=1)
name_rx=dfd3_x.columns
x3=dfd3_x.values

In [48]:
from sklearn import linear_model
model=linear_model.LinearRegression()
model.fit(x3,y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [49]:
a=model.coef_
b=model.intercept_
y_pred=model.predict(x3)

In [52]:
se=np.sum((y-y_pred)**2,axis=0)
se=se/(x3.shape[0]-x3.shape[1]-1)
s=np.linalg.inv(np.dot(x3.T,x3))
stder=np.sqrt(np.diagonal(se*s))

In [53]:
t=a/stder

In [61]:
out4=[]
out4.append(name_rx)
out4.append(a)
out4.append(t)
out4=np.array(out4).T
dfo3=pd.DataFrame(out4)
dfo3.columns=[" 因子名" ,"重み ","t値"]
dfo3

因子名      重み         t値
0      最高  9.54148  0.319135
1      最低  69.6159   1.04338
2  燃焼時間1日  3.90334   4.51459
3  燃焼回数1日  28.5502   2.08576

In [62]:
dfo3.to_csv("重回帰燃焼回数.csv",encoding="shift-jis")